### ISSUE TITLE
TunerButtons example is not working on ESP8266

### ISSUE THREAD

**Issue by TwinsenLGR** [bxparks/AceButton#23]
Hi,
I tested the TunerButtons example on ESP8266 and it doesn't work.
The pins have been changed (D1 to D5) .

On Arduino Pro Mini everything is ok

**Comment by TwinsenLGR** [comment]
The problem was on my ESP board.
I will close the issue.

**Comment by bxparks** [comment]
Glad you figured it out. I was unable to respond because my Arduino boards are boxed up and inaccessible, so I couldn't debug anything.
