### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by seisfeld** [bxparks/AceButton#34]
Hi Brian,

while reading through the new documentation parts of v1.4 I found below typo in [this README.md](https://github.com/bxparks/AceButton/blob/develop/docs/binary_encoding/README.md):

> When each **button** is connected to a single **button**

One _button_ should be _pin_ here I’d assume.

Nice new feature though! Really appreciate the addition and the way this evolved from a GitHub issue into a feature!

Cheers
Stephan

**Comment by bxparks** [comment]
thanks, fixed
