### ISSUE TITLE
call of overloaded AceButton(int) is ambiguous

### ISSUE THREAD

**Issue by joysfera** [bxparks/AceButton#60]
try
```
#define PIN 0
#include <AceButton.h>
using namespace ace_button;
AceButton button(PIN);
```

compiler will complain

`call of overloaded 'AceButton(int)' is ambiguous`

**Comment by bxparks** [comment]
Yeah, it's an unfortunate side-effect of trying to make the constructor a little more flexible and consistent. The C++ compiler cannot distinguish between a `nullptr` and `0`. The solution is:
```C++
AceButton button((uint8_t) PIN);
```
See the **Warning** section towards the end of https://github.com/bxparks/AceButton#AceButtonClass
